# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src
    exclude:
    - azure-pipelines-ci.yml
    - README.md
    - scripts

pool:
  vmImage: ubuntu-latest

variables:
  versionNumber: $(Get-Date -Format yyyy.MM.ddhhmmss)
  buildNumber: $(Build.BuildId)
  configFile: '$(System.DefaultWorkingDirectory)/config.xml'
  cordovaVersionScript: '$(System.DefaultWorkingDirectory)/scripts/Set-CordovaVersion.ps1'

steps:
- task: PowerShell@2
  displayName: 'Set Version and Version Code'
  inputs:
    filePath: $(cordovaVersionScript)
    arguments: >
       -VersionNumber $(versionNumber)
       -BuildNumber $(buildNumber)
       -ConfigFile $(configFile)
- task: NodeTool@0
  inputs:
    versionSpec: '14.15.x'
  displayName: 'Install Node.js'
- task: CmdLine@2
  displayName: 'npm install and build'
  inputs:
    script: 'npm install'
- task: CmdLine@2
  displayName: 'Installation of cordova and Android platform'
  inputs:
    script: |
        npm install -g cordova@11.0.0
        cordova platform add android@9.1.0
- task: CmdLine@2
  displayName: 'Configuring Java SDK'
  inputs:
    script: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        sudo update-alternatives --set java /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java
        sudo update-alternatives --set javac  /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/javac
- task: CmdLine@2
  displayName: 'Generating Android Apps'
  inputs:
    script: |
        cordova build android --release
        cordova build android --debug


