# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: 'Generate new Version'
  inputs:
    targetType: 'inline'
    script: |
      $time =$(Get-Date -Format yyyy.MM.ddhhmmss);
      Write-Host "##vso[task.setvariable variable=Version]$time";
- task: NodeTool@0
  inputs:
    versionSpec: '14.15.x'
  displayName: 'Install Node.js'
- task: CmdLine@2
  displayName: 'npm install and build'
  inputs:
    script: 'npm install'
- task: CmdLine@2
  displayName: 'Install cordova-update-config'
  inputs:
    script: 'npm i -g cordova-update-config'
- task: CmdLine@2
  displayName: 'Update version'
  inputs:
    script: 'cordova-update-config --appversion %VERSION%'
- task: CmdLine@2
  displayName: 'Installation of cordova and Android platform'
  inputs:
    script: |
        npm install -g cordova@11.0.0
        cordova platform add android@9.1.0
- task: CmdLine@2
  displayName: 'Configuring Java SDK'
  inputs:
    script: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep 8 | cut -d " " -f1) || echo '.'
        sudo update-alternatives --config javac
- task: CmdLine@2
  displayName: 'Generating Android Apps'
  inputs:
    script: |
        cordova build android --release
        cordova build android --debug


